version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "npm"
    directory: "/examples"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
